# Generated by Django 5.1.1 on 2024-10-09 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(help_text='Proficiency level from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
