# Generated by Django 5.1.1 on 2024-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contact_alter_company_options_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='https://github.com/olliesharp5'),
        ),
    ]
