# Generated by Django 5.1.1 on 2024-10-23 19:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='skill', validators=[api.models.validate_svg]),
        ),
    ]
