# Generated by Django 5.1.1 on 2024-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_skill_description_alter_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_code_institute',
        ),
        migrations.AddField(
            model_name='project',
            name='is_hackathon',
            field=models.BooleanField(default=False, help_text='Was this project completed during a hackathon?'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='https://github.com/olliesharp5', max_length=300),
        ),
    ]
